spring:
  application:
    name: SciTechNewsParser
  datasource:
    url: jdbc:postgresql://localhost:5433/scitech_newsparser
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 8082
news:
  service:
    url: http://localhost:8083/api/news/list